// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNBRv9QLBpRY7ONJUFp0BhgU8EwIHxSo',
    appId: '1:836718759830:web:f3799f0519d7845478d7b7',
    messagingSenderId: '836718759830',
    projectId: 'farebase-notes-alekslylin',
    authDomain: 'farebase-notes-alekslylin.firebaseapp.com',
    storageBucket: 'farebase-notes-alekslylin.firebasestorage.app',
    measurementId: 'G-ZGLLX4NGHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjNy_IjRuocUwP-DEHSuTqbbjaQ1mkzo',
    appId: '1:836718759830:android:6fb98f7aec3fef8478d7b7',
    messagingSenderId: '836718759830',
    projectId: 'farebase-notes-alekslylin',
    storageBucket: 'farebase-notes-alekslylin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCABT6-lGVdBljaELWBLEop-jP3HZKV8w',
    appId: '1:836718759830:ios:189f887a20db8b6478d7b7',
    messagingSenderId: '836718759830',
    projectId: 'farebase-notes-alekslylin',
    storageBucket: 'farebase-notes-alekslylin.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCABT6-lGVdBljaELWBLEop-jP3HZKV8w',
    appId: '1:836718759830:ios:189f887a20db8b6478d7b7',
    messagingSenderId: '836718759830',
    projectId: 'farebase-notes-alekslylin',
    storageBucket: 'farebase-notes-alekslylin.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNBRv9QLBpRY7ONJUFp0BhgU8EwIHxSo',
    appId: '1:836718759830:web:ba9a0c8012590ea478d7b7',
    messagingSenderId: '836718759830',
    projectId: 'farebase-notes-alekslylin',
    authDomain: 'farebase-notes-alekslylin.firebaseapp.com',
    storageBucket: 'farebase-notes-alekslylin.firebasestorage.app',
    measurementId: 'G-8S39E7LFW0',
  );
}
